### ISSUE TITLE
Error 20100 

### ISSUE THREAD

**Issue by jotarich** [kyle95wm/dwc_network_installer#4]
I tried to create a server . When I try to log using my server in gts pokemon gives an error 20100. In the configurations of the connection gives "successful connection". What am I missing in the server configuration?

**Comment by kyle95wm** [comment]
Is master running?

**Comment by kyle95wm** [comment]
It would've been in the instructions on the DWC wiki:

https://github.com/polaris-/dwc_network_server_emulator/wiki/Setting-up-a-server-from-a-fresh-installation-of-Linux

**Comment by kyle95wm** [comment]
to run master simply type
    python master_server.py 

when you're in the dwc_network_server_emulator folder

**Comment by jotarich** [comment]
I followed the instructions of the site https://github.com/polaris-/dwc_network_server_emulator/wiki/Setting-up-a-server-from-a-fresh-installation-of-Linux

i try this "Using the automated installer script"

**Comment by jotarich** [comment]
ok i run this command

**Comment by kyle95wm** [comment]
yes, thats what I was referring to. You've installed the server, but you need to start the server using the command I gave above.

**Comment by jotarich** [comment]
i run this command but occurs an error 20100 :(

**Comment by jotarich** [comment]
i have to download an specific rom to run this correctly ?

**Comment by kyle95wm** [comment]
Does the console say that the server is listening to connections? 

What IP did you provide during the installation? Private or Public?

Yes you need to patch your ROM to remove HTTPS and replace it with HTTP. There are details on the main DWC wiki on how to do this.

**Comment by jotarich** [comment]
yes ...the console does say that the server is listening to connections on...

during the installation i choose external ip 

i have to run wfc patcher ?

**Comment by jotarich** [comment]
just use the patcher, created a rom with (NoSSL) in the name. When I opened the settings of the game, again gave successful connection but when I opened the game and tried to connect to the GTS has error 20100

**Comment by kyle95wm** [comment]
Not sure what could be causing the error to be honest. Did the server even acknowledge a connection attempt at all by looking at the terminal you have opened with the server running?

This warrants further investigation

**Comment by jotarich** [comment]
> Not sure what could be causing the error to be honest. Did the server even acknowledge a connection attempt at all by looking at the terminal you have opened with the server running?

This warrants further investigation

How do i see this?

**Comment by jotarich** [comment]
this server  104.131.93.87 available in main page is down?

**Comment by kyle95wm** [comment]
you'll see activity in the terminal of the running python script. If you don't see anything then something must be up wit your server.

**Comment by jotarich** [comment]
In the terminal that is running the script is just saying now listering connections ... nothing else appeared

**Comment by kyle95wm** [comment]
Strange! Funny thing is I get this issue too on my own server. Everything was working fine months ago. Perhaps bring this up in the main repo? This script has no problems as far as I can tell as the build is tested every 24 hours and emails me if something broke in the script. Who knows?

**Comment by jotarich** [comment]
Have a test server on the main page, the ip is 104.131.93.87. This is your server? This ip ta also not working, that's why I decided to try to create my own server :)

**Comment by kyle95wm** [comment]
no, my server is 192.241.153.27

**Comment by kyle95wm** [comment]
You could try using my server but idk if it'll work.....

**Comment by jotarich** [comment]
Tested your server ip ... it was something different. When I try to connect to the GTS it saves the game, after that it tries to connect ... this time gave the error 20100 in my ip but in your ip not made the error and continued connecting ... then he ended the connection and saved the game again ... time to enter the GTS room gave an error 52200.
I restarted the game and now gives the error "An error occurred while Attempting to communicate. Turn off the power, restart DS system and try again."

**Comment by kyle95wm** [comment]
Interesting. I know GTS has.....certain things that need to be setup on the server. When building my server I never intended to have support for one game, but rather for any game that can run (i.e mkw)

**Comment by jotarich** [comment]
then unfortunately this is not working out ... unfortunately I do not know much about servers, networks, etc ... but I hope have helped in something. Any doubts about the error just ask! And let me know when you have a new idea on how to solve this ...

**Comment by kyle95wm** [comment]
yeah, sorry I can't be much help.
