### ISSUE TITLE
suggestion: option to fix the 23400 issue

### ISSUE THREAD

**Issue by Marfjeh** [kyle95wm/dwc_network_installer#5]
In issue polaris-/dwc_network_server_emulator/issues/413
Because somethings has changed in apache, we need to have this in apache2.conf to get the emulator working properly.

`HttpProtocolOptions Unsafe LenientMethods Allow0.9`

Maybe a idea to ask the user if he wants it added to his config?

**Comment by kyle95wm** [comment]
If you think this is viable, feel free to open a PR and I'll be happy to merge it.

**Comment by Marfjeh** [comment]
Alright i'll look into it

**Comment by kyle95wm** [comment]
I saw your commit. Don't forget to modify the other install functions. I'll be waiting for your pull request.

**Comment by Marfjeh** [comment]
Yeah i realised yesterday but i didn't got the time atm to do it. haha

**Comment by Marfjeh** [comment]
I've made the pull request. #6
