### ISSUE TITLE
Set the server up, 94020 every time once connected?

### ISSUE THREAD

**Issue by mkCody** [kyle95wm/dwc_network_installer#7]
I've completely set up the server, but once i connect to my server on MKW, i get booted off shortly with the error code 94020. I've completely ran the script correctly and have everything set up. Why is it doing this?

**Comment by kyle95wm** [comment]
I need more details such as the repo you're using. Anyways I spun up a server on my cloud account for you to try out.

**Comment by kyle95wm** [comment]
Closing until further notice since there are no problems on my end.
